---
title: "perturbation_pca"
author: "Kaishin"
date: "2024-06-07"
output: html_document
---

`perturbation_pca` 函数的主要作用是使用 `rank 1 perturbation method` 实时更新主成分分析（PCA），适应每次新增的数据向量。这意味着允许在数据流（如医院每日数据）中逐步更新PCA模型，而不需要每次都对整个数据集重新计算。

相比于 `eigen(cov(mat), TRUE)` 方法（即基础PCA方法），`perturbation_pca` 有以下几个优势：

### 1. **实时性**

`eigen(cov(mat), TRUE)` 是一种批量处理方法，需要在每次更新时重新计算整个协方差矩阵的特征值和特征向量。这对于大数据集来说是非常耗时的。而 `perturbation_pca` 允许在每次接收到新数据时，仅通过`rank 1 perturbation method`快速更新PCA结果，显著减少计算时间，适合频繁的数据处理。

### 2. **计算效率**

因为 `perturbation_pca` 仅进行局部更新，而不是重新计算整个协方差矩阵的特征分解，因此计算复杂度大大降低。对于大规模数据或需要频繁更新的系统，这种方法能够显著节省计算资源。

### 3. **适应性**

`perturbation_pca` 使用遗忘因子`forgetting factor`来平衡新旧数据的影响，可以更好地适应数据分布的动态变化。可以通过调整`forgetting factor`控制模型对新数据的敏感度，适应非平稳数据流。

### 4. **内存占用**

批量方法需要存储整个数据集以计算协方差矩阵，而 `perturbation_pca` 只需要存储当前的主成分和特征值，以及新数据向量。这对于内存有限的环境或分布式系统尤为重要。

### 示例比较

在我们的测试中，我们比较了Eigen和Perturbation两种方法的性能表现。从RMSE和RSE的结果来看，两种方法的精度非常接近，其差异可以忽略不计。这表明在算法的准确性方面，Eigen和Perturbation方法是相当的。

然而，在计算效率方面，两种方法表现出明显的差异。我们分别统计了User Time和Elapsed Time两个指标。User Time表示算法运行过程中，CPU实际花费在计算任务上的时间；而Elapsed Time则包括了CPU计算时间以及其他系统开销，如I/O操作、线程调度等。

对于Eigen方法，User Time为407.80秒，Elapsed Time为911.91秒。两者之间存在较大差距，Elapsed Time是User Time的2.24倍。这说明在Eigen方法的运行过程中，有相当一部分时间花费在了系统开销上。Eigen方法涉及到较多的内存操作和数据交换，导致I/O和线程调度的时间开销较大。

对于Perturbation方法，User Time为37.43秒，Elapsed Time为96.12秒。两者的差距相对较小，Elapsed Time是User Time的2.57倍。这意味着Perturbation方法的计算过程中，CPU有更多的时间用于实际的计算任务，系统开销所占比重更小。Perturbation方法采用了更高效的内存管理和数据访问策略，减少了不必要的I/O操作和线程切换。

综上所述，虽然Eigen和Perturbation方法在精度上无显著差异，但Perturbation方法在计算效率上具有明显优势。Perturbation方法的User Time仅为Eigen方法的9.18%，Elapsed Time也只有Eigen方法的10.54%。在实际应用中，尤其是处理大规模动态数据时，Perturbation方法能够显著减少计算开销，提升整体性能。因此，从计算效率的角度来看，Perturbation方法是更优的选择。

### 适用场景

`perturbation_pca` 特别适用于大规模数据集，内存和计算资源有限的动态数据环境。
